// Copyright 2022 Kato Shinya. All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided the conditions.

// Package imports:
import 'package:test/test.dart';

// Project imports:
import 'package:twitter_api_core/src/service/bcp47_language.dart';

void main() {
  test('.name', () {
    expect(BCP47Language.amharic.name, 'amharic');
    expect(BCP47Language.german.name, 'german');
    expect(BCP47Language.malayalam.name, 'malayalam');
    expect(BCP47Language.slovak.name, 'slovak');
    expect(BCP47Language.arabic.name, 'arabic');
    expect(BCP47Language.greek.name, 'greek');
    expect(BCP47Language.maldivian.name, 'maldivian');
    expect(BCP47Language.slovenian.name, 'slovenian');
    expect(BCP47Language.armenian.name, 'armenian');
    expect(BCP47Language.gujarati.name, 'gujarati');
    expect(BCP47Language.marathi.name, 'marathi');
    expect(BCP47Language.soraniKurdish.name, 'soraniKurdish');
    expect(BCP47Language.basque.name, 'basque');
    expect(BCP47Language.haitianCreole.name, 'haitianCreole');
    expect(BCP47Language.nepali.name, 'nepali');
    expect(BCP47Language.spanish.name, 'spanish');
    expect(BCP47Language.bengali.name, 'bengali');
    expect(BCP47Language.hebrew.name, 'hebrew');
    expect(BCP47Language.norwegian.name, 'norwegian');
    expect(BCP47Language.swedish.name, 'swedish');
    expect(BCP47Language.bosnian.name, 'bosnian');
    expect(BCP47Language.hindi.name, 'hindi');
    expect(BCP47Language.oriya.name, 'oriya');
    expect(BCP47Language.tagalog.name, 'tagalog');
    expect(BCP47Language.bulgarian.name, 'bulgarian');
    expect(BCP47Language.latinizedHindi.name, 'latinizedHindi');
    expect(BCP47Language.panjabi.name, 'panjabi');
    expect(BCP47Language.tamil.name, 'tamil');
    expect(BCP47Language.burmese.name, 'burmese');
    expect(BCP47Language.hungarian.name, 'hungarian');
    expect(BCP47Language.pashto.name, 'pashto');
    expect(BCP47Language.telugu.name, 'telugu');
    expect(BCP47Language.croatian.name, 'croatian');
    expect(BCP47Language.icelandic.name, 'icelandic');
    expect(BCP47Language.persian.name, 'persian');
    expect(BCP47Language.thai.name, 'thai');
    expect(BCP47Language.catalan.name, 'catalan');
    expect(BCP47Language.indonesian.name, 'indonesian');
    expect(BCP47Language.polish.name, 'polish');
    expect(BCP47Language.tibetan.name, 'tibetan');
    expect(BCP47Language.czech.name, 'czech');
    expect(BCP47Language.italian.name, 'italian');
    expect(BCP47Language.portuguese.name, 'portuguese');
    expect(BCP47Language.traditionalChinese.name, 'traditionalChinese');
    expect(BCP47Language.danish.name, 'danish');
    expect(BCP47Language.japanese.name, 'japanese');
    expect(BCP47Language.romanian.name, 'romanian');
    expect(BCP47Language.turkish.name, 'turkish');
    expect(BCP47Language.dutch.name, 'dutch');
    expect(BCP47Language.kannada.name, 'kannada');
    expect(BCP47Language.russian.name, 'russian');
    expect(BCP47Language.ukrainian.name, 'ukrainian');
    expect(BCP47Language.english.name, 'english');
    expect(BCP47Language.khmer.name, 'khmer');
    expect(BCP47Language.serbian.name, 'serbian');
    expect(BCP47Language.urdu.name, 'urdu');
    expect(BCP47Language.estonian.name, 'estonian');
    expect(BCP47Language.korean.name, 'korean');
    expect(BCP47Language.simplifiedChinese.name, 'simplifiedChinese');
    expect(BCP47Language.uyghur.name, 'uyghur');
    expect(BCP47Language.finnish.name, 'finnish');
    expect(BCP47Language.lao.name, 'lao');
    expect(BCP47Language.sindhi.name, 'sindhi');
    expect(BCP47Language.vietnamese.name, 'vietnamese');
    expect(BCP47Language.french.name, 'french');
    expect(BCP47Language.latvian.name, 'latvian');
    expect(BCP47Language.sinhala.name, 'sinhala');
    expect(BCP47Language.welsh.name, 'welsh');
    expect(BCP47Language.georgian.name, 'georgian');
    expect(BCP47Language.lithuanian.name, 'lithuanian');
  });

  test('.code', () {
    expect(BCP47Language.amharic.code, 'am');
    expect(BCP47Language.german.code, 'de');
    expect(BCP47Language.malayalam.code, 'ml');
    expect(BCP47Language.slovak.code, 'sk');
    expect(BCP47Language.arabic.code, 'ar');
    expect(BCP47Language.greek.code, 'el');
    expect(BCP47Language.maldivian.code, 'dv');
    expect(BCP47Language.slovenian.code, 'sl');
    expect(BCP47Language.armenian.code, 'hy');
    expect(BCP47Language.gujarati.code, 'gu');
    expect(BCP47Language.marathi.code, 'mr');
    expect(BCP47Language.soraniKurdish.code, 'ckb');
    expect(BCP47Language.basque.code, 'eu');
    expect(BCP47Language.haitianCreole.code, 'ht');
    expect(BCP47Language.nepali.code, 'ne');
    expect(BCP47Language.spanish.code, 'es');
    expect(BCP47Language.bengali.code, 'bn');
    expect(BCP47Language.hebrew.code, 'iw');
    expect(BCP47Language.norwegian.code, 'no');
    expect(BCP47Language.swedish.code, 'sv');
    expect(BCP47Language.bosnian.code, 'bs');
    expect(BCP47Language.hindi.code, 'hi');
    expect(BCP47Language.oriya.code, 'or');
    expect(BCP47Language.tagalog.code, 'tl');
    expect(BCP47Language.bulgarian.code, 'bg');
    expect(BCP47Language.latinizedHindi.code, 'hi-Latn');
    expect(BCP47Language.panjabi.code, 'pa');
    expect(BCP47Language.tamil.code, 'ta');
    expect(BCP47Language.burmese.code, 'my');
    expect(BCP47Language.hungarian.code, 'hu');
    expect(BCP47Language.pashto.code, 'ps');
    expect(BCP47Language.telugu.code, 'te');
    expect(BCP47Language.croatian.code, 'hr');
    expect(BCP47Language.icelandic.code, 'is');
    expect(BCP47Language.persian.code, 'fa');
    expect(BCP47Language.thai.code, 'th');
    expect(BCP47Language.catalan.code, 'ca');
    expect(BCP47Language.indonesian.code, 'in');
    expect(BCP47Language.polish.code, 'pl');
    expect(BCP47Language.tibetan.code, 'bo');
    expect(BCP47Language.czech.code, 'cs');
    expect(BCP47Language.italian.code, 'it');
    expect(BCP47Language.portuguese.code, 'pt');
    expect(BCP47Language.traditionalChinese.code, 'zh-TW');
    expect(BCP47Language.danish.code, 'da');
    expect(BCP47Language.japanese.code, 'ja');
    expect(BCP47Language.romanian.code, 'ro');
    expect(BCP47Language.turkish.code, 'tr');
    expect(BCP47Language.dutch.code, 'nl');
    expect(BCP47Language.kannada.code, 'kn');
    expect(BCP47Language.russian.code, 'ru');
    expect(BCP47Language.ukrainian.code, 'uk');
    expect(BCP47Language.english.code, 'en');
    expect(BCP47Language.khmer.code, 'km');
    expect(BCP47Language.serbian.code, 'sr');
    expect(BCP47Language.urdu.code, 'ur');
    expect(BCP47Language.estonian.code, 'et');
    expect(BCP47Language.korean.code, 'ko');
    expect(BCP47Language.simplifiedChinese.code, 'zh-CN');
    expect(BCP47Language.uyghur.code, 'ug');
    expect(BCP47Language.finnish.code, 'fi');
    expect(BCP47Language.lao.code, 'lo');
    expect(BCP47Language.sindhi.code, 'sd');
    expect(BCP47Language.vietnamese.code, 'vi');
    expect(BCP47Language.french.code, 'fr');
    expect(BCP47Language.latvian.code, 'lv');
    expect(BCP47Language.sinhala.code, 'si');
    expect(BCP47Language.welsh.code, 'cy');
    expect(BCP47Language.georgian.code, 'ka');
    expect(BCP47Language.lithuanian.code, 'lt');
  });
}
